# add the following to _config.yml file
title: Rhaven Nelson
logo: /assets/img/Rhaven_Nelson2.png
description: data science portfolio
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
